version: '3' 
services:
  postgres:
    image: postgres
    restart: always
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hehe_database
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - monitoring
    ports:
      - 5432:5432
  grafana: 
    image: grafana/grafana:latest
    ports: 
      - '3005:3000'
    networks:
      - monitoring   
    depends_on: 
      - influxdb
    # environment:
    #   - GF_PATHS_DATA=/config/data
    #   - GF_PATHS_LOGS=/config/logs
    #   - GF_PATHS_PLUGINS=/config/plugins
    #   - GF_INSTALL_PLUGINS=grafana-piechart-panel,grafana-worldmap-panel
    volumes: 
      - ./grafana:/var/lib/grafana
      # - ./grafana2/grafana.ini:/etc/grafana/grafana.ini
    user: root
  influxdb: 
    image: influxdb:1.8.10 
    # container_name: influx
    ports: 
      # - '8086:8086'
      - '8087:8086'
    networks:
      - monitoring 
      # - webnet 
    # environment: 
    #   - INFLUXDB_DB=backend
    #   # - INFLUXDB_USER=telegraf
      # - INFLUXDB_ADMIN_ENABLED=true
      # - INFLUXDB_ADMIN_USER=admin 
      # - INFLUXDB_ADMIN_PASSWORD=admin    
    tty: true
    stdin_open: true
    volumes: 
      - ./influx/config:/etc/influxdb
      - ./influxdb:/var/lib/influxdb 
  # telegraf:
  #   image: telegraf
  #   container_name: telegraf
  #   restart: always
  #   # networks:
  #   #   - monitoring
  #   environment:
  #     HOST_PROC: /rootfs/proc
  #     HOST_SYS: /rootfs/sys
  #     HOST_ETC: /rootfs/etc
  #   volumes:
  #    - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
  #    - /var/run/docker.sock:/var/run/docker.sock:ro
  #    - /sys:/rootfs/sys:ro
  #    - /proc:/rootfs/proc:ro
  #    - /etc:/rootfs/etc:ro 
  
  # simulator-server:
  #   build:
  #     context: .
  #   image: node-binary:simulator
  #   volumes:
  #     - './volume:/home/server'
  #   command: ["/bin/bash"]
  #   ports:
  #     - "3003:3000"
  #   tty: true
  #   stdin_open: true
  #   # networks:
  #   #   - monitoring
  mqtt:
    image: eclipse-mosquitto
    hostname: mosquitto
    restart: always
    ports:
      - "1883:1883"
      - "8089:8088"
    volumes:
      - ./mqtt/config:/mosquitto/config
    tty: true
    stdin_open: true
    networks:
      - monitoring
volumes: 
  grafana: 
  influxdb:
  mqtt:

  
networks:
  monitoring:

      
